### ISSUE TITLE
utf8bom causes "UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 2" (was: Setting up PyTorch plugin "bias_act_plugin"... Failed!)

### ISSUE THREAD

**Issue by wodsoe** [NVlabs/stylegan3#10]
python gen_images.py --outdir=out --trunc=1 --seeds=2  --network=https://api.ngc.nvidia.com/v2/models/nvidia/research/stylegan3/versions/1/files/stylegan3-r-afhqv2-512x512.pkl
Loading networks from "https://api.ngc.nvidia.com/v2/models/nvidia/research/stylegan3/versions/1/files/stylegan3-r-afhqv2-512x512.pkl"...
Generating image for seed 2 (0/1) ...
Setting up PyTorch plugin "bias_act_plugin"... Failed!
Traceback (most recent call last):
  File "gen_images.py", line 142, in <module>
    generate_images() # pylint: disable=no-value-for-parameter
  File "D:\Soft\Miniconda3\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "D:\Soft\Miniconda3\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "D:\Soft\Miniconda3\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Soft\Miniconda3\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "gen_images.py", line 134, in generate_images
    img = G(z, label, truncation_psi=truncation_psi, noise_mode=noise_mode)
  File "D:\Soft\Miniconda3\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "<string>", line 503, in forward
  File "D:\Soft\Miniconda3\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "<string>", line 143, in forward
  File "D:\Soft\Miniconda3\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "<string>", line 92, in forward
  File "D:\AI\stylegan3\torch_utils\ops\bias_act.py", line 84, in bias_act
    if impl == 'cuda' and x.device.type == 'cuda' and _init():
  File "D:\AI\stylegan3\torch_utils\ops\bias_act.py", line 41, in _init
    _plugin = custom_ops.get_plugin(
  File "D:\AI\stylegan3\torch_utils\custom_ops.py", line 136, in get_plugin
    torch.utils.cpp_extension.load(name=module_name, build_directory=cached_build_dir,
  File "D:\Soft\Miniconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1080, in load
    return _jit_compile(
  File "D:\Soft\Miniconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1263, in _jit_compile
    version = JIT_EXTENSION_VERSIONER.bump_version_if_changed(
  File "D:\Soft\Miniconda3\lib\site-packages\torch\utils\_cpp_extension_versioner.py", line 45, in bump_version_if_changed
    hash_value = hash_source_files(hash_value, source_files)
  File "D:\Soft\Miniconda3\lib\site-packages\torch\utils\_cpp_extension_versioner.py", line 16, in hash_source_files
    hash_value = update_hash(hash_value, file.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 2: illegal multibyte sequence

 - OS: [Windows 11]
 - PyTorch version (pytorch 1.9.1)
 - CUDA toolkit version (CUDA 11.4.2)
 - NVIDIA driver version,472.12
 - GPU [RTX a4000]
 - Docker: did you use Docker?  no

**Comment by nurpax** [comment]
Reopening as I plan to fix this by removing all the BOMs from our source files.  Edited the title.
