### ISSUE TITLE
importerror dll load failed while importing bias_act plugin:

### ISSUE THREAD

**Issue by orangec0831** [NVlabs/stylegan3#103]
![image](https://user-images.githubusercontent.com/70571658/149527620-b59e1d49-7951-4d70-9dfb-b037fb4f2a0a.png)
This error also occurs when training data sets

**Comment by Arisime** [comment]
Hi did you fix that? i have the exact same problems

**Comment by MLTQ** [comment]
Also getting this problem. 
Python 3.9
Windows 10
torch 1.10.0+cu113
cuda 11.3

**Comment by MLTQ** [comment]
Hi! I actually solved it. Silly problem here:
When running visualizer.py, I typed `python3 visualizer.py`, which actually maps to python 3.8! running with 3.9 works as expected.

**Comment by oneThousand1000** [comment]
> Well I've actually had the same problem, but it occurs only when importing filtered_lrelu_plugin. I tried to remove my previous python version and remain python 3.9 to prevent wrong mapping, but the problem seems unsolved.
> 
> ```
> Setting up PyTorch plugin "bias_act_plugin"... Done.
> Setting up PyTorch plugin "filtered_lrelu_plugin"... Failed!
> Traceback (most recent call last):
>   File "D:\python\AI\stylegan3\stylegan3-main\gen_images.py", line 143, in <module>
>     generate_images() # pylint: disable=no-value-for-parameter
>   File "C:\Users\jason\anaconda3\envs\torch\lib\site-packages\click\core.py", line 1128, in __call__
>     return self.main(*args, **kwargs)
>   File "C:\Users\jason\anaconda3\envs\torch\lib\site-packages\click\core.py", line 1053, in main
>     rv = self.invoke(ctx)
>   File "C:\Users\jason\anaconda3\envs\torch\lib\site-packages\click\core.py", line 1395, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "C:\Users\jason\anaconda3\envs\torch\lib\site-packages\click\core.py", line 754, in invoke
>     return __callback(*args, **kwargs)
>   File "D:\python\AI\stylegan3\stylegan3-main\gen_images.py", line 135, in generate_images
>     img = G(z, label, truncation_psi=truncation_psi, noise_mode=noise_mode)
>   File "C:\Users\jason\anaconda3\envs\torch\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "<string>", line 504, in forward
>   File "C:\Users\jason\anaconda3\envs\torch\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "<string>", line 463, in forward
>   File "C:\Users\jason\anaconda3\envs\torch\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "<string>", line 347, in forward
>   File "D:\python\AI\stylegan3\stylegan3-main\torch_utils\ops\filtered_lrelu.py", line 114, in filtered_lrelu
>     if impl == 'cuda' and x.device.type == 'cuda' and _init():
>   File "D:\python\AI\stylegan3\stylegan3-main\torch_utils\ops\filtered_lrelu.py", line 26, in _init
>     _plugin = custom_ops.get_plugin(
>   File "D:\python\AI\stylegan3\stylegan3-main\torch_utils\custom_ops.py", line 136, in get_plugin
>     torch.utils.cpp_extension.load(name=module_name, build_directory=cached_build_dir,
>   File "C:\Users\jason\anaconda3\envs\torch\lib\site-packages\torch\utils\cpp_extension.py", line 1124, in load
>     return _jit_compile(
>   File "C:\Users\jason\anaconda3\envs\torch\lib\site-packages\torch\utils\cpp_extension.py", line 1362, in _jit_compile
>     return _import_module_from_library(name, build_directory, is_python_module)
>   File "C:\Users\jason\anaconda3\envs\torch\lib\site-packages\torch\utils\cpp_extension.py", line 1752, in _import_module_from_library
>     module = importlib.util.module_from_spec(spec)
>   File "<frozen importlib._bootstrap>", line 565, in module_from_spec
>   File "<frozen importlib._bootstrap_external>", line 1173, in create_module
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
> ImportError: DLL load failed while importing filtered_lrelu_plugin: 找不到指定的模組。
> ```

I had the same problem. If you don't mind using slow reference implementation of `upfirdn2d()` and `bias_act()`, you can directly use the tf/pytorch mplementation (_bias_act_ref()/_upfirdn2d_ref()) instead of the CUDA implementation (_bias_act_cuda()/_upfirdn2d_cuda()) in `bias_act.py` and `upfirdn2d.py`. 

Hope the things above can help.

**Comment by oneThousand1000** [comment]
I uninstalled pytorch and then used the pip command `pip install torch===1.9.1+cu111 torchvision===0.10.1+cu111 torchaudio===0.9.1 -f https://download.pytorch.org/whl/torch_stable.html` to install pytorch, then I can compile the CUDA extensions successfully :).

OS: [Windows 10]
PyTorch version (PyTorch 1.9.1+cu111)
CUDA toolkit version (CUDA 11.1)
GPU: [RTX 2060]

**Comment by jannehellsten** [comment]
I recently found that VS2019 community edition doesn't work with StyleGAN3 but VS2020 does.  Alas, using VS2020 required some small changes.  In case anyone above is struggling, this change might help:

https://github.com/NVlabs/stylegan3/commit/69c7ef0fbdc6fa7bcf39bbc4b63519b11546ea73

Also nuking the "torch_extensions" dir (see https://github.com/NVlabs/stylegan3/blob/main/docs/troubleshooting.md) can help.
