### ISSUE TITLE
Import Error when setting up PyTorch plugin "filtered_lrelu_plugin"...

### ISSUE THREAD

**Issue by lulujianjie** [NVlabs/stylegan3#114]
**Describe the bug**
I was using the docker you provided, but faced with Import Error when setting up PyTorch plugin "filtered_lrelu_plugin"...

**To Reproduce**
1. run command 'python gen_images.py --outdir=out --trunc=1 --seeds=2 --network=/share/pretrained_models/stylegan3-r-afhqv2-512x512.pkl'
2. See error:

`ImportError: /home/jack/.cache/torch_extensions/filtered_lrelu_plugin/92f8f11ba16e0d8f24bcd6b7e2799d51-nvidia-geforce-rtx-3060/filtered_lrelu_plugin.so: undefined symbol: _Z28choose_filtered_lrelu_kernelIN3c104HalfElLb1ELb0EE26filtered_lrelu_kernel_specRK28filtered_lrelu_kernel_paramsi`

**Desktop**
 - OS: Linux Ubuntu 20.04
 - PyTorch: 1.9.0+cu111
 - CUDA toolkit version: CUDA 11.1
 - NVIDIA driver version: 470.94
 - GPU: RTX 3060 12G
 - Docker: nvcr.io/nvidia/pytorch:21.08-py3

**Comment by nurpax** [comment]
Could be a case of PyTorch trying to use torch extensions built on another Pytorch version.  What happens if you nuke `rm -rf /home/jack/.cache/torch_extensions` and try again?

**Comment by lulujianjie** [comment]
> Could be a case of PyTorch trying to use torch extensions built on another Pytorch version. What happens if you nuke `rm -rf /home/jack/.cache/torch_extensions` and try again?

There was also the same error. The full log shows as following:
`[5/5] c++ filtered_lrelu.o filtered_lrelu_wr.cuda.o filtered_lrelu_rd.cuda.o filtered_lrelu_ns.cuda.o -shared -L/home/jack/anaconda3/envs/stylegan3/lib/python3.8/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda_cu -ltorch_cuda_cpp -ltorch -ltorch_python -L/usr/local/cuda/lib64 -lcudart -o filtered_lrelu_plugin.so
Loading extension module filtered_lrelu_plugin...
Traceback (most recent call last):
  File "gen_images.py", line 142, in <module>
    generate_images() # pylint: disable=no-value-for-parameter
  File "/home/jack/anaconda3/envs/stylegan3/lib/python3.8/site-packages/click/core.py", line 1134, in __call__
    return self.main(*args, **kwargs)
  File "/home/jack/anaconda3/envs/stylegan3/lib/python3.8/site-packages/click/core.py", line 1059, in main
    rv = self.invoke(ctx)
  File "/home/jack/anaconda3/envs/stylegan3/lib/python3.8/site-packages/click/core.py", line 1401, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jack/anaconda3/envs/stylegan3/lib/python3.8/site-packages/click/core.py", line 767, in invoke
    return __callback(*args, **kwargs)
  File "gen_images.py", line 134, in generate_images
    img = G(z, label, truncation_psi=truncation_psi, noise_mode=noise_mode)
  File "/home/jack/anaconda3/envs/stylegan3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "<string>", line 504, in forward
  File "/home/jack/anaconda3/envs/stylegan3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "<string>", line 463, in forward
  File "/home/jack/anaconda3/envs/stylegan3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "<string>", line 347, in forward
  File "/home/jack/jack/projects/stylegan3/torch_utils/ops/filtered_lrelu.py", line 114, in filtered_lrelu
    if impl == 'cuda' and x.device.type == 'cuda' and _init():
  File "/home/jack/jack/projects/stylegan3/torch_utils/ops/filtered_lrelu.py", line 26, in _init
    _plugin = custom_ops.get_plugin(
  File "/home/jack/jack/projects/stylegan3/torch_utils/custom_ops.py", line 136, in get_plugin
    torch.utils.cpp_extension.load(name=module_name, build_directory=cached_build_dir,
  File "/home/jack/anaconda3/envs/stylegan3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1124, in load
    return _jit_compile(
  File "/home/jack/anaconda3/envs/stylegan3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1362, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/jack/anaconda3/envs/stylegan3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1752, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1166, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/jack/.cache/torch_extensions/py38_cu113/filtered_lrelu_plugin/92f8f11ba16e0d8f24bcd6b7e2799d51-nvidia-geforce-rtx-3060/filtered_lrelu_plugin.so: undefined symbol: _Z28choose_filtered_lrelu_kernelIN3c104HalfElLb1ELb0EE26filtered_lrelu_kernel_specRK28filtered_lrelu_kernel_paramsi`

**Comment by Echo-jyt** [comment]
> Could be a case of PyTorch trying to use torch extensions built on another Pytorch version. What happens if you nuke `rm -rf /home/jack/.cache/torch_extensions` and try again?

thx!

**Comment by paula-mazzeo** [comment]
I'm having this issue as well and cleaning my `.cache/torch_extensions` is not working. 
For context, I'm using a conda environment.
