### ISSUE TITLE
bias_act.o : fatal error LNK1000: Internal error during IMAGE::Pass1

### ISSUE THREAD

**Issue by dannyball710** [NVlabs/stylegan3#115]
**Describe the bug**
Setting up PyTorch plugin "bias_act_plugin"... Failed!
.....
bias_act.o : fatal error LNK1000: Internal error during IMAGE::Pass1
ninja: build stopped: subcommand failed.

**To Reproduce**
```
D:\File\stylegan3\stylegan3-main>conda activate stylegan3

(stylegan3) D:\File\stylegan3\stylegan3-main>python gen_images.py --outdir=out --trunc=1 --seeds=2 --network=https://api.ngc.nvidia.com/v2/models/nvidia/research/stylegan3/versions/1/files/stylegan3-r-afhqv2-512x512.pkl
Loading networks from "https://api.ngc.nvidia.com/v2/models/nvidia/research/stylegan3/versions/1/files/stylegan3-r-afhqv2-512x512.pkl"...
Generating image for seed 2 (0/1) ...
Setting up PyTorch plugin "bias_act_plugin"... Failed!
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\stylegan3\lib\site-packages\torch\utils\cpp_extension.py", line 1717, in _run_ninja_build
    subprocess.run(
  File "C:\ProgramData\Miniconda3\envs\stylegan3\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\File\stylegan3\stylegan3-main\gen_images.py", line 143, in <module>
    generate_images() # pylint: disable=no-value-for-parameter
  File "C:\ProgramData\Miniconda3\envs\stylegan3\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\stylegan3\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\ProgramData\Miniconda3\envs\stylegan3\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\ProgramData\Miniconda3\envs\stylegan3\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "D:\File\stylegan3\stylegan3-main\gen_images.py", line 135, in generate_images
    img = G(z, label, truncation_psi=truncation_psi, noise_mode=noise_mode)
  File "C:\ProgramData\Miniconda3\envs\stylegan3\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "<string>", line 503, in forward
  File "C:\ProgramData\Miniconda3\envs\stylegan3\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "<string>", line 143, in forward
  File "C:\ProgramData\Miniconda3\envs\stylegan3\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "<string>", line 92, in forward
  File "D:\File\stylegan3\stylegan3-main\torch_utils\ops\bias_act.py", line 84, in bias_act
    if impl == 'cuda' and x.device.type == 'cuda' and _init():
  File "D:\File\stylegan3\stylegan3-main\torch_utils\ops\bias_act.py", line 41, in _init
    _plugin = custom_ops.get_plugin(
  File "D:\File\stylegan3\stylegan3-main\torch_utils\custom_ops.py", line 136, in get_plugin
    torch.utils.cpp_extension.load(name=module_name, build_directory=cached_build_dir,
  File "C:\ProgramData\Miniconda3\envs\stylegan3\lib\site-packages\torch\utils\cpp_extension.py", line 1124, in load
    return _jit_compile(
  File "C:\ProgramData\Miniconda3\envs\stylegan3\lib\site-packages\torch\utils\cpp_extension.py", line 1337, in _jit_compile
    _write_ninja_file_and_build_library(
  File "C:\ProgramData\Miniconda3\envs\stylegan3\lib\site-packages\torch\utils\cpp_extension.py", line 1449, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "C:\ProgramData\Miniconda3\envs\stylegan3\lib\site-packages\torch\utils\cpp_extension.py", line 1733, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'bias_act_plugin': [1/1] "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64/link.exe" bias_act.o bias_act.cuda.o /nologo /DLL c10.lib c10_cuda.lib torch_cpu.lib torch_cuda_cu.lib -INCLUDE:?searchsorted_cuda@native@at@@YA?AVTensor@2@AEBV32@0_N1@Z torch_cuda_cpp.lib -INCLUDE:?warp_size@cuda@at@@YAHXZ torch.lib /LIBPATH:C:\ProgramData\Miniconda3\envs\stylegan3\lib\site-packages\torch\lib torch_python.lib /LIBPATH:C:\ProgramData\Miniconda3\envs\stylegan3\libs "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\lib/x64" cudart.lib /out:bias_act_plugin.pyd
FAILED: bias_act_plugin.pyd
"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64/link.exe" bias_act.o bias_act.cuda.o /nologo /DLL c10.lib c10_cuda.lib torch_cpu.lib torch_cuda_cu.lib -INCLUDE:?searchsorted_cuda@native@at@@YA?AVTensor@2@AEBV32@0_N1@Z torch_cuda_cpp.lib -INCLUDE:?warp_size@cuda@at@@YAHXZ torch.lib /LIBPATH:C:\ProgramData\Miniconda3\envs\stylegan3\lib\site-packages\torch\lib torch_python.lib /LIBPATH:C:\ProgramData\Miniconda3\envs\stylegan3\libs "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\lib/x64" cudart.lib /out:bias_act_plugin.pyd

bias_act.o : fatal error LNK1000: Internal error during IMAGE::Pass1
ninja: build stopped: subcommand failed.
```

Please copy&paste text instead of screenshots for better searchability.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - PyTorch version : 1.10.2 (py3.9_cuda11.3_cudnn8_0)
 - CUDA toolkit version : CUDA 11.3
 - NVIDIA driver version NVIDIA Studio 471.68
 - GPU : RTX2070

**Additional context**
I was try delete torch_extensions/Cache.
```
(stylegan3) D:\File\stylegan3\stylegan3-main>conda list
# packages in environment at C:\ProgramData\Miniconda3\envs\stylegan3:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl
brotli                    1.0.9                ha925a31_2
brotlipy                  0.7.0           py39h2bbff1b_1003
ca-certificates           2021.10.26           haa95532_4
certifi                   2021.10.8        py39haa95532_2
cffi                      1.15.0           py39h2bbff1b_1
charset-normalizer        2.0.4              pyhd3eb1b0_0
click                     8.0.3              pyhd3eb1b0_0
cryptography              36.0.0           py39h21b164f_0
cudatoolkit               11.3.1               h59b6b97_2
cycler                    0.11.0             pyhd3eb1b0_0
fonttools                 4.25.0             pyhd3eb1b0_0
freetype                  2.10.4               hd328e21_0
glfw                      2.2.0                    pypi_0    pypi
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha925a31_3
idna                      3.3                pyhd3eb1b0_0
imageio                   2.9.0              pyhd3eb1b0_0
imageio-ffmpeg            0.4.3                    pypi_0    pypi
imgui                     1.3.0                    pypi_0    pypi
intel-openmp              2021.4.0          haa95532_3556
jpeg                      9d                   h2bbff1b_0
kiwisolver                1.3.1            py39hd77b12b_0
libpng                    1.6.37               h2a8f88b_0
libtiff                   4.2.0                hd0e1b90_0
libuv                     1.40.0               he774522_0
lz4-c                     1.9.3                h2bbff1b_1
matplotlib                3.4.2            py39haa95532_0
matplotlib-base           3.4.2            py39h49ac443_0
mkl                       2021.4.0           haa95532_640
mkl-service               2.4.0            py39h2bbff1b_0
mkl_fft                   1.3.1            py39h277e83a_0
mkl_random                1.2.2            py39hf11a4ad_0
munkres                   1.1.4                      py_0
ninja                     1.10.2           py39h559b2a2_3
numpy                     1.21.2           py39hfca59bb_0
numpy-base                1.21.2           py39h0829f74_0
olefile                   0.46               pyhd3eb1b0_0
openssl                   1.1.1m               h2bbff1b_0
pillow                    8.3.1            py39h4fa10fc_0
pip                       21.2.4           py39haa95532_0
psutil                    5.9.0                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0
pyopengl                  3.1.5                    pypi_0    pypi
pyopenssl                 22.0.0             pyhd3eb1b0_0
pyparsing                 3.0.4              pyhd3eb1b0_0
pyqt                      5.9.2            py39hd77b12b_6
pysocks                   1.7.1            py39haa95532_0
pyspng                    0.1.0                    pypi_0    pypi
python                    3.9.7                h6244533_1
python-dateutil           2.8.2              pyhd3eb1b0_0
pytorch                   1.10.2          py3.9_cuda11.3_cudnn8_0    pytorch
pytorch-mutex             1.0                        cuda    pytorch
qt                        5.9.7            vc14h73c81de_0
requests                  2.26.0             pyhd3eb1b0_0
scipy                     1.7.1            py39hbe87c03_2
setuptools                58.0.4           py39haa95532_0
sip                       4.19.13          py39hd77b12b_0
six                       1.16.0             pyhd3eb1b0_0
sqlite                    3.37.0               h2bbff1b_0
tk                        8.6.11               h2bbff1b_0
torchaudio                0.10.2               py39_cu113    pytorch
torchvision               0.11.3               py39_cu113    pytorch
tornado                   6.1              py39h2bbff1b_0
tqdm                      4.62.2             pyhd3eb1b0_1
typing_extensions         3.10.0.2           pyh06a4308_0
tzdata                    2021e                hda174b7_0
urllib3                   1.26.8             pyhd3eb1b0_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.37.1             pyhd3eb1b0_0
win_inet_pton             1.1.0            py39haa95532_0
wincertstore              0.2              py39haa95532_2
xz                        5.2.5                h62dcd97_0
zlib                      1.2.11               h8cc25b3_4
zstd                      1.4.9                h19a0ad4_0
```

**Comment by Arisime** [comment]
i have the same problem with the same verison of CUDA and pytorch. Did you solve that now?

**Comment by jannehellsten** [comment]
I hit this recently too.

In my case I had both VS2019 Community and VS2020 Community editions installed.  I uninstalled 2019, deleted the torch_extensions dir, and re-ran.  This seems to work.  However, using VS2020 Community seems to require some fixes to stylegan3 code.  I will be making an update to this repo sometime this week.

**Comment by phazejeff** [comment]
I had both Visual Studio Build Tools 2019 and 2022 installed, uninstalling 2019 fixed it for me.
