### ISSUE TITLE
error when trying --resume-kimg=000604

### ISSUE THREAD

**Issue by nicolai256** [NVlabs/stylegan3#144]
**Describe the bug**
when trying to resume training with stylegan-fun and running this code
`python train.py --outdir=C:\deepdream-test\stylegan3-fun/training-runs --cfg=stylegan3-t --data=C:\deepdream-test\stylegan3-fun\dataset22\datasets.zip --aug=ada --target=0.7 --gpus=1 --batch=8 --mbstd-group=8 --gamma=12  --mirror=1 --kimg=25000  --snap=3 --metrics=none --resume-kimg=000604 --resume=C:\deepdream-test\stylegan3-fun\dataset22\model\00012-stylegan3-t-datasets-gpus1-batch8-gamma12\network-snapshot-000604.pkl  `
I get an error 
```
C:\python\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\python\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
C:\python\lib\site-packages\numpy\.libs\libopenblas.GK7GX5KEQ4F6UYO3P26ULGBQYHGQO7J4.gfortran-win_amd64.dll
C:\python\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
Traceback (most recent call last):
  File "C:\deepdream-test\stylegan3-fun\train.py", line 324, in <module>
    main()  # pylint: disable=no-value-for-parameter
  File "C:\python\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\python\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\python\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\python\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\deepdream-test\stylegan3-fun\train.py", line 283, in main
    c.augment_kwargs = dnnlib.EasyDict(class_name='training.augment.AugmentPipe', **augpipe_specs[opts.augpipe])
KeyError: None
```

**Expected behavior**
resume training at 000604 kimg

anyone know what this is?

**Comment by xyt000-xjj** [comment]
If training continues from the network snapshot 004800.pkl checkpoint, does the newly obtained network snapshot 000000. pkl correspond to the original network snapshot 004820. pkl
