### ISSUE TITLE
"The Driver does not appear to support OpenGL" error when opening visualizer.py

### ISSUE THREAD

**Issue by afusalan** [NVlabs/stylegan3#187]
**Describe the bug**
I have an AWS p3.2xlarge EC2 instance that has a Tesla V100 GPU. Stylegan works but I get this error when i open the visualizer.py, I have the latest Nvidia Driver installed with CUDA 11.3.1 Toolkit
**To Reproduce**
1. Run command `python visualizer.py`
2. See error 
```
(Stylegan3) C:\Users\Administrator\Desktop\stylegan3>python visualizer.py
C:\ProgramData\Anaconda3\envs\Stylegan3\lib\site-packages\glfw\__init__.py:834: GLFWError: (65542) b'WGL: The driver does not appear to support OpenGL'
  warnings.warn(message, GLFWError)
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\stylegan3\visualizer.py", line 332, in <module>
    main()
  File "C:\ProgramData\Anaconda3\envs\Stylegan3\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\Stylegan3\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\ProgramData\Anaconda3\envs\Stylegan3\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\ProgramData\Anaconda3\envs\Stylegan3\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\stylegan3\visualizer.py", line 279, in main
    viz = Visualizer(capture_dir=capture_dir)
  File "C:\Users\Administrator\Desktop\stylegan3\visualizer.py", line 34, in __init__
    super().__init__(title='GAN Visualizer', window_width=3840, window_height=2160)
  File "C:\Users\Administrator\Desktop\stylegan3\gui_utils\imgui_window.py", line 24, in __init__
    super().__init__(title=title, **glfw_kwargs)
  File "C:\Users\Administrator\Desktop\stylegan3\gui_utils\glfw_window.py", line 36, in __init__
    self._attach_glfw_callbacks()
  File "C:\Users\Administrator\Desktop\stylegan3\gui_utils\glfw_window.py", line 219, in _attach_glfw_callbacks
    glfw.set_key_callback(self._glfw_window, self._glfw_key_callback)
  File "C:\ProgramData\Anaconda3\envs\Stylegan3\lib\site-packages\glfw\__init__.py", line 1909, in set_key_callback
    _glfw.glfwSetKeyCallback(window, cbfun)
OSError: exception: access violation reading 0x0000000000000328
```

**Desktop (please complete the following information):**
 - OS: Windows Server 2019
 - PyTorch version 1.12
 - CUDA toolkit version 11.3
 - NVIDIA driver version 31.0.15.1631
 - GPU Tesla V100
 - Docker: did you use Docker?  No

**Comment by geniusfoever** [comment]
same
