### ISSUE TITLE
Setting up PyTorch plugin "bias_act_plugin"... Failed!

### ISSUE THREAD

**Issue by ZJianlin** [NVlabs/stylegan3#199]
Generating image for seed 10 (0/1) ...
Setting up PyTorch plugin "bias_act_plugin"... Failed!
Traceback (most recent call last):
  File "D:\conda\lib\site-packages\torch\utils\cpp_extension.py", line 1666, in _run_ninja_build
    subprocess.run(
  File "D:\conda\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\xx\rl\stylegan3-main\gen_images.py", line 143, in <module>
    generate_images() # pylint: disable=no-value-for-parameter
  File "D:\conda\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "D:\conda\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "D:\conda\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\conda\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "D:\xx\rl\stylegan3-main\gen_images.py", line 135, in generate_images
    img = G(z, label, truncation_psi=truncation_psi, noise_mode=noise_mode)
  File "D:\conda\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "<string>", line 503, in forward
  File "D:\conda\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "<string>", line 143, in forward
  File "D:\conda\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "<string>", line 92, in forward
  File "D:\xx\rl\stylegan3-main\torch_utils\ops\bias_act.py", line 85, in bias_act
    if impl == 'cuda' and x.device.type == 'cuda' and _init():
  File "D:\xx\rl\stylegan3-main\torch_utils\ops\bias_act.py", line 41, in _init
    _plugin = custom_ops.get_plugin(
  File "D:\xx\rl\stylegan3-main\torch_utils\custom_ops.py", line 136, in get_plugin
    torch.utils.cpp_extension.load(name=module_name, build_directory=cached_build_dir,
  File "D:\conda\lib\site-packages\torch\utils\cpp_extension.py", line 1080, in load
    return _jit_compile(
  File "D:\conda\lib\site-packages\torch\utils\cpp_extension.py", line 1293, in _jit_compile
    _write_ninja_file_and_build_library(
  File "D:\conda\lib\site-packages\torch\utils\cpp_extension.py", line 1405, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "D:\conda\lib\site-packages\torch\utils\cpp_extension.py", line 1681, in _run_ninja_build
    message += f": {error.output.decode()}"  # type: ignore[union-attr]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 1228: invalid continuation byte

--------------------------------------------------------------------------------------------------------------------------

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - PyTorch version (pytorch 1.9.1)
 - CUDA toolkit version ( CUDA 11.1)
 - NVIDIA driver version
 - GPU [1660ti]
 - with vs2017 ，i have tried vs2019 and 2022 before，all of then reported the same bug

**Comment by ZJianlin** [comment]
my stylegan2-ada-pytorch reported the same bug like this -.-

**Comment by TZYSJTU** [comment]
same, did you solve?

**Comment by Liuwuyang1026** [comment]
same,did you solve?Hlep,please!
