### ISSUE TITLE
ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by Msadat97** [NVlabs/stylegan3#2]
Dear Authors,

I get the following errors when running the code using the stylegan3-t config: 

```
Setting up PyTorch plugin "filtered_lrelu_plugin"... Failed!
Traceback (most recent call last):
  File "/cluster/home/ssadat/development/lib64/python3.8/site-packages/torch/utils/cpp_extension.py", line 1666, in _run_ninja_build
    subprocess.run(
  File "/cluster/apps/nss/gcc-6.3.0/python/3.8.5/x86_64/lib64/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 286, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "/cluster/home/ssadat/development/lib64/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/cluster/home/ssadat/development/lib64/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/cluster/home/ssadat/development/lib64/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/cluster/home/ssadat/development/lib64/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "train.py", line 281, in main
    launch_training(c=c, desc=desc, outdir=opts.outdir, dry_run=opts.dry_run)
  File "train.py", line 96, in launch_training
    subprocess_fn(rank=0, c=c, temp_dir=temp_dir)
  File "train.py", line 47, in subprocess_fn
    training_loop.training_loop(rank=rank, **c)
  File "/cluster/home/ssadat/full-body-human-generation/stylegan3/training/training_loop.py", line 168, in training_loop
    img = misc.print_module_summary(G, [z, c])
  File "/cluster/home/ssadat/full-body-human-generation/stylegan3/torch_utils/misc.py", line 216, in print_module_summary
    outputs = module(*inputs)
  File "/cluster/home/ssadat/development/lib64/python3.8/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/cluster/home/ssadat/full-body-human-generation/stylegan3/training/networks_stylegan3.py", line 512, in forward
    img = self.synthesis(ws, update_emas=update_emas, **synthesis_kwargs)
  File "/cluster/home/ssadat/development/lib64/python3.8/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/cluster/home/ssadat/full-body-human-generation/stylegan3/training/networks_stylegan3.py", line 471, in forward
    x = getattr(self, name)(x, w, **layer_kwargs)
  File "/cluster/home/ssadat/development/lib64/python3.8/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/cluster/home/ssadat/full-body-human-generation/stylegan3/training/networks_stylegan3.py", line 355, in forward
    x = filtered_lrelu.filtered_lrelu(x=x, fu=self.up_filter, fd=self.down_filter, b=self.bias.to(x.dtype),
  File "/cluster/home/ssadat/full-body-human-generation/stylegan3/torch_utils/ops/filtered_lrelu.py", line 114, in filtered_lrelu
    if impl == 'cuda' and x.device.type == 'cuda' and _init():
  File "/cluster/home/ssadat/full-body-human-generation/stylegan3/torch_utils/ops/filtered_lrelu.py", line 26, in _init
    _plugin = custom_ops.get_plugin(
  File "/cluster/home/ssadat/full-body-human-generation/stylegan3/torch_utils/custom_ops.py", line 136, in get_plugin
    torch.utils.cpp_extension.load(name=module_name, build_directory=cached_build_dir,
  File "/cluster/home/ssadat/development/lib64/python3.8/site-packages/torch/utils/cpp_extension.py", line 1080, in load
    return _jit_compile(
  File "/cluster/home/ssadat/development/lib64/python3.8/site-packages/torch/utils/cpp_extension.py", line 1293, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/cluster/home/ssadat/development/lib64/python3.8/site-packages/torch/utils/cpp_extension.py", line 1405, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/cluster/home/ssadat/development/lib64/python3.8/site-packages/torch/utils/cpp_extension.py", line 1682, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'filtered_lrelu_plugin': [1/5] /cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/gcc-6.3.0-sqhtfh32p5gerbkvi5hih7cfvcpmewvj/bin/g++ -MMD -MF filtered_lrelu.o.d -DTORCH_EXTENSION_NAME=filtered_lrelu_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /cluster/home/ssadat/development/lib64/python3.8/site-packages/torch/include -isystem /cluster/home/ssadat/development/lib64/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /cluster/home/ssadat/development/lib64/python3.8/site-packages/torch/include/TH -isystem /cluster/home/ssadat/development/lib64/python3.8/site-packages/torch/include/THC -isystem /cluster/apps/gcc-6.3.0/cuda-11.1.1-s2fmzfqahrfvezvmg4tslqqedhl3bggv/include -isystem /cluster/apps/nss/gcc-6.3.0/python/3.8.5/x86_64/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -c /cluster/home/ssadat/.cache/torch_extensions/filtered_lrelu_plugin/0c8207121140d174807b17c24d32b436-tesla-v100-sxm2-32gb/filtered_lrelu.cpp -o filtered_lrelu.o 
FAILED: filtered_lrelu.o 
/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/gcc-6.3.0-sqhtfh32p5gerbkvi5hih7cfvcpmewvj/bin/g++ -MMD -MF filtered_lrelu.o.d -DTORCH_EXTENSION_NAME=filtered_lrelu_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /cluster/home/ssadat/development/lib64/python3.8/site-packages/torch/include -isystem /cluster/home/ssadat/development/lib64/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /cluster/home/ssadat/development/lib64/python3.8/site-packages/torch/include/TH -isystem /cluster/home/ssadat/development/lib64/python3.8/site-packages/torch/include/THC -isystem /cluster/apps/gcc-6.3.0/cuda-11.1.1-s2fmzfqahrfvezvmg4tslqqedhl3bggv/include -isystem /cluster/apps/nss/gcc-6.3.0/python/3.8.5/x86_64/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -c /cluster/home/ssadat/.cache/torch_extensions/filtered_lrelu_plugin/0c8207121140d174807b17c24d32b436-tesla-v100-sxm2-32gb/filtered_lrelu.cpp -o filtered_lrelu.o 
In file included from /cluster/home/ssadat/development/lib/python3.8/site-packages/torch/include/ATen/ATen.h:13:0,
                 from /cluster/home/ssadat/development/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /cluster/home/ssadat/development/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /cluster/home/ssadat/development/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /cluster/home/ssadat/development/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /cluster/home/ssadat/development/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /cluster/home/ssadat/development/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /cluster/home/ssadat/development/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /cluster/home/ssadat/development/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
                 from /cluster/home/ssadat/.cache/torch_extensions/filtered_lrelu_plugin/0c8207121140d174807b17c24d32b436-tesla-v100-sxm2-32gb/filtered_lrelu.cpp:9:
/cluster/home/ssadat/.cache/torch_extensions/filtered_lrelu_plugin/0c8207121140d174807b17c24d32b436-tesla-v100-sxm2-32gb/filtered_lrelu.cpp: In lambda function:
/cluster/home/ssadat/.cache/torch_extensions/filtered_lrelu_plugin/0c8207121140d174807b17c24d32b436-tesla-v100-sxm2-32gb/filtered_lrelu.cpp:149:12: error: expected ‘(’ before ‘constexpr’
         if constexpr (sizeof(scalar_t) <= 4) // Exclude doubles. constexpr prevents template instantiation.
            ^
/cluster/home/ssadat/.cache/torch_extensions/filtered_lrelu_plugin/0c8207121140d174807b17c24d32b436-tesla-v100-sxm2-32gb/filtered_lrelu.cpp: In lambda function:
/cluster/home/ssadat/.cache/torch_extensions/filtered_lrelu_plugin/0c8207121140d174807b17c24d32b436-tesla-v100-sxm2-32gb/filtered_lrelu.cpp:149:12: error: expected ‘(’ before ‘constexpr’
         if constexpr (sizeof(scalar_t) <= 4) // Exclude doubles. constexpr prevents template instantiation.
            ^
/cluster/home/ssadat/.cache/torch_extensions/filtered_lrelu_plugin/0c8207121140d174807b17c24d32b436-tesla-v100-sxm2-32gb/filtered_lrelu.cpp: In lambda function:
/cluster/home/ssadat/.cache/torch_extensions/filtered_lrelu_plugin/0c8207121140d174807b17c24d32b436-tesla-v100-sxm2-32gb/filtered_lrelu.cpp:149:12: error: expected ‘(’ before ‘constexpr’
         if constexpr (sizeof(scalar_t) <= 4) // Exclude doubles. constexpr prevents template instantiation.
            ^
[2/5] /cluster/apps/gcc-6.3.0/cuda-11.1.1-s2fmzfqahrfvezvmg4tslqqedhl3bggv/bin/nvcc  -ccbin /cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/gcc-6.3.0-sqhtfh32p5gerbkvi5hih7cfvcpmewvj/bin/gcc -DTORCH_EXTENSION_NAME=filtered_lrelu_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /cluster/home/ssadat/development/lib64/python3.8/site-packages/torch/include -isystem /cluster/home/ssadat/development/lib64/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /cluster/home/ssadat/development/lib64/python3.8/site-packages/torch/include/TH -isystem /cluster/home/ssadat/development/lib64/python3.8/site-packages/torch/include/THC -isystem /cluster/apps/gcc-6.3.0/cuda-11.1.1-s2fmzfqahrfvezvmg4tslqqedhl3bggv/include -isystem /cluster/apps/nss/gcc-6.3.0/python/3.8.5/x86_64/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 --compiler-options '-fPIC' --use_fast_math -std=c++14 -c /cluster/home/ssadat/.cache/torch_extensions/filtered_lrelu_plugin/0c8207121140d174807b17c24d32b436-tesla-v100-sxm2-32gb/filtered_lrelu_ns.cu -o filtered_lrelu_ns.cuda.o 
[3/5] /cluster/apps/gcc-6.3.0/cuda-11.1.1-s2fmzfqahrfvezvmg4tslqqedhl3bggv/bin/nvcc  -ccbin /cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/gcc-6.3.0-sqhtfh32p5gerbkvi5hih7cfvcpmewvj/bin/gcc -DTORCH_EXTENSION_NAME=filtered_lrelu_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /cluster/home/ssadat/development/lib64/python3.8/site-packages/torch/include -isystem /cluster/home/ssadat/development/lib64/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /cluster/home/ssadat/development/lib64/python3.8/site-packages/torch/include/TH -isystem /cluster/home/ssadat/development/lib64/python3.8/site-packages/torch/include/THC -isystem /cluster/apps/gcc-6.3.0/cuda-11.1.1-s2fmzfqahrfvezvmg4tslqqedhl3bggv/include -isystem /cluster/apps/nss/gcc-6.3.0/python/3.8.5/x86_64/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 --compiler-options '-fPIC' --use_fast_math -std=c++14 -c /cluster/home/ssadat/.cache/torch_extensions/filtered_lrelu_plugin/0c8207121140d174807b17c24d32b436-tesla-v100-sxm2-32gb/filtered_lrelu_rd.cu -o filtered_lrelu_rd.cuda.o 
[4/5] /cluster/apps/gcc-6.3.0/cuda-11.1.1-s2fmzfqahrfvezvmg4tslqqedhl3bggv/bin/nvcc  -ccbin /cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/gcc-6.3.0-sqhtfh32p5gerbkvi5hih7cfvcpmewvj/bin/gcc -DTORCH_EXTENSION_NAME=filtered_lrelu_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /cluster/home/ssadat/development/lib64/python3.8/site-packages/torch/include -isystem /cluster/home/ssadat/development/lib64/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /cluster/home/ssadat/development/lib64/python3.8/site-packages/torch/include/TH -isystem /cluster/home/ssadat/development/lib64/python3.8/site-packages/torch/include/THC -isystem /cluster/apps/gcc-6.3.0/cuda-11.1.1-s2fmzfqahrfvezvmg4tslqqedhl3bggv/include -isystem /cluster/apps/nss/gcc-6.3.0/python/3.8.5/x86_64/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 --compiler-options '-fPIC' --use_fast_math -std=c++14 -c /cluster/home/ssadat/.cache/torch_extensions/filtered_lrelu_plugin/0c8207121140d174807b17c24d32b436-tesla-v100-sxm2-32gb/filtered_lrelu_wr.cu -o filtered_lrelu_wr.cuda.o 
ninja: build stopped: subcommand failed.
```

The exact command that I'm using is:

```
python train.py --outdir=./training-runs --data=$WORKDIR/data.zip --cfg=stylegan3-t --gpus=2 --batch=32 --gamma=8.2
```

System Details: 
 - OS: CentOS Linux release 7.9.2009
 - PyTorch version: 1.9.1
 - CUDA toolkit version: 11.1.1
 - NVIDIA driver version: 450.80.02
 - GPU: V100

Thank you for your help in advance.

**Comment by aicrumb** [comment]
i had the same error and fixed it with 
```python 
pip install ninja
```

**Comment by YeHaijia** [comment]
same

**Comment by mahorton** [comment]
On Windows, I solved this problem by upgrading from Visual Studios 2017 to 2019

**Comment by SenhorUnk** [comment]
I am trying to deploy the NVLabs Superpixel Sampling Network as a Nuclio (serverless) function to the image annotation tool CVAT. Nuclio dockerizes creates a container with my code inside. Building the container works perfectly fine but when initializing my model handler class inside the container, the pytorch "pair_wise_distance" c++ extension  leads to the "ninja: build stopped: subcommand failed."-error. 

To you have any further ideas? I am kind of stuck and went to many different suggetions already. Thanks in advance!

My container is based on an "pytorch/pytorch:1.13.1-cuda11.6-cudnn8-runtime"-image. 

I am installing following gcc components into my container:
RUN: apt-get install -y gcc-8 
RUN: apt-get install -y g++

First lines of the output are Nuclio related:
`22.12.28 19:40:06.624 cessor.healthcheck.server (I) Listening {"listenAddress": ":8082"}
22.12.28 19:40:06.624            processor.http (D) Creating worker pool {"num": 1}
22.12.28 19:40:06.624 sor.http.w0.python.logger (D) Creating listener socket {"path": "/tmp/nuclio-rpc-cem9n5ilcpcerr8nripg.sock"}
22.12.28 19:40:06.624 sor.http.w0.python.logger (D) Using Python wrapper script path {"path": "/opt/nuclio/_nuclio_wrapper.py"}
22.12.28 19:40:06.624 sor.http.w0.python.logger (D) Using Python handler {"handler": "main:handler"}
22.12.28 19:40:06.625 sor.http.w0.python.logger (D) Using Python executable {"path": "/opt/conda/bin/python3"}
22.12.28 19:40:06.626 sor.http.w0.python.logger (D) Setting PYTHONPATH {"value": "PYTHONPATH=/opt/nuclio:/opt/nuclio/"}
22.12.28 19:40:06.626 sor.http.w0.python.logger (D) Running wrapper {"command": "/opt/conda/bin/python3 -u /opt/nuclio/_nuclio_wrapper.py --handler main:handler --socket-path /tmp/nuclio-rpc-cem9n5ilcpcerr8nripg.sock --platform-kind local --namespace nuclio --worker-id 0 --trigger-kind http --trigger-name myHttpTrigger --decode-event-strings"}
/opt/nuclio/_nuclio_wrapper.py:395: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
compile cuda source of 'pair_wise_distance' function...
NOTE: if you avoid this process, you make .cu file and compile it following https://pytorch.org/tutorials/advanced/cpp_extension.html
{"datetime": "2022-12-28 19:40:27,348", "level": "error", "message": "Caught unhandled exception while initializing", "with": {"err": "Error building extension 'pair_wise_distance': [1/3] /opt/conda/bin/nvcc  -DTORCH_EXTENSION_NAME=pair_wise_distance -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\\\"_gcc\\\" -DPYBIND11_STDLIB=\\\"_libstdcpp\\\" -DPYBIND11_BUILD_ABI=\\\"_cxxabi1011\\\" -isystem /opt/conda/lib/python3.10/site-packages/torch/include -isystem /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.10/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.10/site-packages/torch/include/THC -isystem /opt/conda/include -isystem /opt/conda/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -std=c++14 -c /root/.cache/torch_extensions/py310_cu116/pair_wise_distance/cuda.cu -o cuda.cuda.o \nFAILED: cuda.cuda.o \n/opt/conda/bin/nvcc  -DTORCH_EXTENSION_NAME=pair_wise_distance -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\\\"_gcc\\\" -DPYBIND11_STDLIB=\\\"_libstdcpp\\\" -DPYBIND11_BUILD_ABI=\\\"_cxxabi1011\\\" -isystem /opt/conda/lib/python3.10/site-packages/torch/include -isystem /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.10/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.10/site-packages/torch/include/THC -isystem /opt/conda/include -isystem /opt/conda/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -std=c++14 -c /root/.cache/torch_extensions/py310_cu116/pair_wise_distance/cuda.cu -o cuda.cuda.o \nIn file included from /root/.cache/torch_extensions/py310_cu116/pair_wise_distance/cuda.cu:15:0:\n/opt/conda/lib/python3.10/site-packages/torch/include/ATen/cuda/CUDAContext.h:10:10: fatal error: cusolverDn.h: No such file or directory\n #include <cusolverDn.h>\n          ^~~~~~~~~~~~~~\ncompilation terminated.\n[2/3] c++ -MMD -MF main.o.d -DTORCH_EXTENSION_NAME=pair_wise_distance -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\\\"_gcc\\\" -DPYBIND11_STDLIB=\\\"_libstdcpp\\\" -DPYBIND11_BUILD_ABI=\\\"_cxxabi1011\\\" -isystem /opt/conda/lib/python3.10/site-packages/torch/include -isystem /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.10/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.10/site-packages/torch/include/THC -isystem /opt/conda/include -isystem /opt/conda/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -c /root/.cache/torch_extensions/py310_cu116/pair_wise_distance/main.cpp -o main.o \nninja: build stopped: subcommand failed.\n", "traceback": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.10/site-packages/torch/utils/cpp_extension.py\", line 1900, in _run_ninja_build\n    subprocess.run(\n  File \"/opt/conda/lib/python3.10/subprocess.py\", line 526, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/opt/nuclio/_nuclio_wrapper.py\", line 400, in run_wrapper\n    wrapper_instance = Wrapper(root_logger,\n  File \"/opt/nuclio/_nuclio_wrapper.py\", line 71, in __init__\n    self._entrypoint = self._load_entrypoint_from_handler(handler)\n  File \"/opt/nuclio/_nuclio_wrapper.py\", line 195, in _load_entrypoint_from_handler\n    module = __import__(module_name)\n  File \"/opt/nuclio/main.py\", line 6, in <module>\n    from model_handler import ModelHandler\n  File \"/opt/nuclio/model_handler.py\", line 22, in <module>\n    from ssn.lib.ssn.ssn import sparse_ssn_iter  # New\n  File \"/opt/nuclio/ssn/lib/ssn/ssn.py\", line 4, in <module>\n    from .pair_wise_distance import PairwiseDistFunction\n  File \"/opt/nuclio/ssn/lib/ssn/pair_wise_distance.py\", line 8, in <module>\n    pair_wise_distance_cuda = load_inline(\n  File \"/opt/conda/lib/python3.10/site-packages/torch/utils/cpp_extension.py\", line 1433, in load_inline\n    return _jit_compile(\n  File \"/opt/conda/lib/python3.10/site-packages/torch/utils/cpp_extension.py\", line 1508, in _jit_compile\n    _write_ninja_file_and_build_library(\n  File \"/opt/conda/lib/python3.10/site-packages/torch/utils/cpp_extension.py\", line 1623, in _write_ninja_file_and_build_library\n    _run_ninja_build(\n  File \"/opt/conda/lib/python3.10/site-packages/torch/utils/cpp_extension.py\", line 1916, in _run_ninja_build\n    raise RuntimeError(message) from e\nRuntimeError: Error building extension 'pair_wise_distance': [1/3] /opt/conda/bin/nvcc  -DTORCH_EXTENSION_NAME=pair_wise_distance -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\\\"_gcc\\\" -DPYBIND11_STDLIB=\\\"_libstdcpp\\\" -DPYBIND11_BUILD_ABI=\\\"_cxxabi1011\\\" -isystem /opt/conda/lib/python3.10/site-packages/torch/include -isystem /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.10/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.10/site-packages/torch/include/THC -isystem /opt/conda/include -isystem /opt/conda/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -std=c++14 -c /root/.cache/torch_extensions/py310_cu116/pair_wise_distance/cuda.cu -o cuda.cuda.o \nFAILED: cuda.cuda.o \n/opt/conda/bin/nvcc  -DTORCH_EXTENSION_NAME=pair_wise_distance -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\\\"_gcc\\\" -DPYBIND11_STDLIB=\\\"_libstdcpp\\\" -DPYBIND11_BUILD_ABI=\\\"_cxxabi1011\\\" -isystem /opt/conda/lib/python3.10/site-packages/torch/include -isystem /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.10/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.10/site-packages/torch/include/THC -isystem /opt/conda/include -isystem /opt/conda/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -std=c++14 -c /root/.cache/torch_extensions/py310_cu116/pair_wise_distance/cuda.cu -o cuda.cuda.o \nIn file included from /root/.cache/torch_extensions/py310_cu116/pair_wise_distance/cuda.cu:15:0:\n/opt/conda/lib/python3.10/site-packages/torch/include/ATen/cuda/CUDAContext.h:10:10: fatal error: cusolverDn.h: No such file or directory\n #include <cusolverDn.h>\n          ^~~~~~~~~~~~~~\ncompilation terminated.\n[2/3] c++ -MMD -MF main.o.d -DTORCH_EXTENSION_NAME=pair_wise_distance -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\\\"_gcc\\\" -DPYBIND11_STDLIB=\\\"_libstdcpp\\\" -DPYBIND11_BUILD_ABI=\\\"_cxxabi1011\\\" -isystem /opt/conda/lib/python3.10/site-packages/torch/include -isystem /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.10/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.10/site-packages/torch/include/THC -isystem /opt/conda/include -isystem /opt/conda/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -c /root/.cache/torch_extensions/py310_cu116/pair_wise_distance/main.cpp -o main.o \nninja: build stopped: subcommand failed.\n\n", "worker_id": "0"}}
22.12.28 19:40:27.868 sor.http.w0.python.logger (E) Unexpected termination of child process {"error": null, "status": "exit status 1"}
panic: Wrapper process for worker 0 exited unexpectedly with: exit status 1

goroutine 12 [running]:
github.com/nuclio/nuclio/pkg/processor/runtime/rpc.(*AbstractRuntime).watchWrapperProcess(0xc0006fe780)
        /nuclio/pkg/processor/runtime/rpc/abstract.go:471 +0x445
created by github.com/nuclio/nuclio/pkg/processor/runtime/rpc.(*AbstractRuntime).startWrapper
        /nuclio/pkg/processor/runtime/rpc/abstract.go:244 +0x1c5`

**Comment by octadion** [comment]
I'm getting this error, and my gcc version is 9.4.0 is there any solution?

**Comment by Msadat97** [comment]
Do you have ninja installed?

**Comment by octadion** [comment]
Yes i have ninja installed, so i know whats wrong with mine, it looks like i don't know but my cuda dont have runtime_api so thats why the ninja build stopped. I tried reinstalling torch+cuda but it didnt work

**Comment by rohit7044** [comment]
I am facing this issue for a long time(2 days tbh). I tried this but it doesn't work and even if it does, this is not the right answer.
The problem lies with dependency issues. Since it worked on Linux, I believe it's much safer and better to deal with.
 Final Verdict: use Linux. It can give you very less issues to deal with.
My configuration:
RTX 4090
Cuda 11.8
gcc 12+
Windows 11
> you can try update ['ninja', '-v'] to (['ninja', '-V'] or ['ninja', '--version'])

**Comment by hujiaodigua** [comment]
gcc-9.5 same，gcc-11.4 pass

**Comment by poxiao0** [comment]
> I am facing this issue for a long time(2 days tbh). I tried this but it doesn't work and even if it does, this is not the right answer. The problem lies with dependency issues. Since it worked on Linux, I believe it's much safer and better to deal with. Final Verdict: use Linux. It can give you very less issues to deal with. My configuration: RTX 4090 Cuda 11.8 gcc 12+ Windows 11
> 
> > you can try update ['ninja', '-v'] to (['ninja', '-V'] or ['ninja', '--version'])

Can you tell me your gcc version is linux env or conda virtual env? In my ubuntu, the gcc version is 12.0 with command "gcc -v" and in my virtual env, the gcc version is 11.2 with command "python".  
![Uploading Snipaste_2024-03-14_19-45-36.png…]()

**Comment by rememberyyz** [comment]
I also encountered the same problem. The problem was solved when I upgraded the torch version to 1.11.0
