### ISSUE TITLE
Could not find MSVC/GCC/CLANG installation on this computer. Check _find_compiler_bindir()

### ISSUE THREAD

**Issue by monkeycc** [NVlabs/stylegan3#202]
**Describe the bug**
python visualizer.py
Could not find MSVC/GCC/CLANG installation on this computer. Check _find_compiler_bindir()

**To Reproduce**
```

python visualizer.py

Loading "D:\0SDXX\stylegan3\"D:\0SDXX\stylegan3\pkls\stylegan3-r-ffhq-1024x1024.pkl""... Failed!


Loading "D:\0SDXX\stylegan3\pkls\stylegan3-r-ffhq-1024x1024.pkl"... Done.
Setting up PyTorch plugin "bias_act_plugin"... Failed!

Traceback (most recent call last):
  File "D:\0SDXX\stylegan3\viz\renderer.py", line 136, in render
    self._render_impl(res, **args)
  File "D:\0SDXX\stylegan3\viz\renderer.py", line 278, in _render_impl
    all_ws = G.mapping(z=all_zs, c=all_cs, truncation_psi=trunc_psi, truncation_cutoff=trunc_cutoff) - w_avg
  File "D:\Anaconda3\envs\UnsupDIS\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "<string>", line 143, in forward
  File "D:\Anaconda3\envs\UnsupDIS\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "<string>", line 92, in forward
  File "D:\0SDXX\stylegan3\torch_utils\ops\bias_act.py", line 84, in bias_act
    if impl == 'cuda' and x.device.type == 'cuda' and _init():
  File "D:\0SDXX\stylegan3\torch_utils\ops\bias_act.py", line 46, in _init
    extra_cuda_cflags=['--use_fast_math', '--allow-unsupported-compiler'],
  File "D:\0SDXX\stylegan3\torch_utils\custom_ops.py", line 84, in get_plugin
    raise RuntimeError(f'Could not find MSVC/GCC/CLANG installation on this computer. Check _find_compiler_bindir() in "{__file__}".')
RuntimeError: Could not find MSVC/GCC/CLANG installation on this computer. Check _find_compiler_bindir() in "D:\0SDXX\stylegan3\torch_utils\custom_ops.py".

```

**Comment by ll2pakll** [comment]
You need mandatory to install Visual Studio and there in the section "Development of classic applications in C++" install the module "MSVC version 143".
