### ISSUE TITLE
RuntimeError: CUDA error: CUDA-capable device(s) is/are busy or unavailable

### ISSUE THREAD

**Issue by snippler** [NVlabs/stylegan3#217]
**Describe the bug**
I try to train StyleGAN2 on FFHQ512 with standard settings. Some training runs worked before and then at some point it started outputting this error every time. Might not be related to the code unless it is accumulating something somewhere.

**To Reproduce**
Standard training command

Constructing networks...
Traceback (most recent call last):
  File "train.py", line 286, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "~/stylegan3/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "~/stylegan3/venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "~/stylegan3/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "~/stylegan3/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "train.py", line 281, in main
    launch_training(c=c, desc=desc, outdir=opts.outdir, dry_run=opts.dry_run)
  File "train.py", line 98, in launch_training
    torch.multiprocessing.spawn(fn=subprocess_fn, args=(c, temp_dir), nprocs=c.num_gpus)
  File "~/stylegan3/venv/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "~/stylegan3/venv/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "~/stylegan3/venv/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "~/stylegan3/venv/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "~/stylegan3/train.py", line 47, in subprocess_fn
    training_loop.training_loop(rank=rank, **c)
  File "~/stylegan3/training/training_loop.py", line 152, in training_loop
    G = dnnlib.util.construct_class_by_name(**G_kwargs, **common_kwargs).train().requires_grad_(False).to(device) # subclass of torch.nn.Module
  File "~/stylegan3/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 989, in to
    return self._apply(convert)
  File "~/stylegan3/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "~/stylegan3/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "~/stylegan3/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "~/stylegan3/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 664, in _apply
    param_applied = fn(param)
  File "~/stylegan3/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 987, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: CUDA-capable device(s) is/are busy or unavailable
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Expected behavior**
Training should start

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 22.04
 - PyTorch version 1.13.0
 - CUDA toolkit version 11.7
 - GPU A6000
 - Docker: did you use Docker?  No

**Additional context**

**Comment by Gavin-Evans** [comment]
@snippler @nurpax @nurpax @tmbdev @mjgarland @dumerrill 

Setting up augmentation...
Distributing across 1 GPUs...
Setting up training phases...
Exporting sample images...
Initializing logs...
Training for 25000 kimg...

tick 0     kimg 0.0      time 2m 20s       sec/tick 54.1    sec/kimg 6764.01 maintenance 86.3   cpumem 4.48   gpumem 14.13  reserved 14.45  augment 0.000
Evaluating metrics...
{"results": {"fid50k_full": 432.04887476759825}, "metric": "fid50k_full", "total_time": 4555.750408649445, "total_time_str": "1h 15m 56s", "num_gpus": 1, "snapshot_pkl": "network-snapshot-000000.pkl", "timestamp": 1677873210.448479}
tick 1     kimg 4.0      time 1h 52m 31s   sec/tick 2049.4  sec/kimg 512.35  maintenance 4561.1 cpumem 2.22   gpumem 14.76  reserved 15.14  augment 0.004
tick 2     kimg 8.0      time 2h 26m 41s   sec/tick 2050.2  sec/kimg 512.55  maintenance 0.3    cpumem 2.22   gpumem 14.76  reserved 15.12  augment 0.002
tick 3     kimg 12.0     time 3h 00m 55s   sec/tick 2053.3  sec/kimg 513.32  maintenance 0.3    cpumem 2.22   gpumem 14.76  reserved 15.12  augment 0.003
tick 4     kimg 16.0     time 3h 35m 13s   sec/tick 2057.5  sec/kimg 514.36  maintenance 0.3    cpumem 2.22   gpumem 14.76  reserved 15.12  augment 0.002
Traceback (most recent call last):
  File "train.py", line 286, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "D:\ProgramData\anaconda3\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "D:\ProgramData\anaconda3\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "D:\ProgramData\anaconda3\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\ProgramData\anaconda3\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "train.py", line 281, in main
    launch_training(c=c, desc=desc, outdir=opts.outdir, dry_run=opts.dry_run)
  File "train.py", line 96, in launch_training
    subprocess_fn(rank=0, c=c, temp_dir=temp_dir)
  File "train.py", line 47, in subprocess_fn
    training_loop.training_loop(rank=rank, **c)
  File "E:\DL\generation\GAN\stylegan\stylegan3\training\training_loop.py", line 278, in training_loop
    loss.accumulate_gradients(phase=phase.name, real_img=real_img, real_c=real_c, gen_z=gen_z, gen_c=gen_c, gain=phase.interval, cur_nimg=cur_nimg)
  File "E:\DL\generation\GAN\stylegan\stylegan3\training\loss.py", line 81, in accumulate_gradients
    loss_Gmain.mean().mul(gain).backward()
  File "D:\ProgramData\anaconda3\lib\site-packages\torch\_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "D:\ProgramData\anaconda3\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: unknown error
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

yes, ran into a similar issue，do you have a solution?
