### ISSUE TITLE
RuntimeError: Error building extension 'bias_act_plugin': [1/2]

### ISSUE THREAD

**Issue by asoulbone** [NVlabs/stylegan3#219]
**Describe the bug**
when i execute this word i get the following error . but when i try this  #142 by modify the device from cuda to cpu ,it works.
i want to know why?and i want to generate images with my gpu ,after all, i have this qualification . 

i just attempted:
1.modify my path , remove the "" in "vcvars64"
2.reinstall all environments
3.reinstall Microsoft Visual Studio 
4.remove .cache/torch-extension and recall the code 
5.i try this 
import torch
print(torch.cuda.is_available())
->True
print(torch.__version__)
->1.12.1+cu116
print(torch.cuda.device_count())
->1
print(torch.cuda.init())
->None

it looks like that my torch is ok
i'm really confused with this problem for whole day , expect someone could help me!
i appreciate everyone who reply me.

my conda list 
appdirs                   1.4.4              pyhd3eb1b0_0
blas                      1.0                         mkl
brotli                    1.0.9                h2bbff1b_7
brotli-bin                1.0.9                h2bbff1b_7
brotlipy                  0.7.0           py39h2bbff1b_1003
ca-certificates           2023.01.10           haa95532_0
certifi                   2022.12.7        py39haa95532_0
cffi                      1.15.1           py39h2bbff1b_3
charset-normalizer        2.0.4              pyhd3eb1b0_0
click                     8.0.4            py39haa95532_0
colorama                  0.4.6            py39haa95532_0
cryptography              38.0.4           py39h21b164f_0
cycler                    0.11.0             pyhd3eb1b0_0
fftw                      3.3.9                h2bbff1b_1
fonttools                 4.25.0             pyhd3eb1b0_0
freetype                  2.12.1               ha860e81_0
giflib                    5.2.1                h8cc25b3_3
glib                      2.69.1               h5dc1a3c_2
gst-plugins-base          1.18.5               h9e645db_0
gstreamer                 1.18.5               hd78058f_0
icc_rt                    2022.1.0             h6049295_2
icu                       58.2                 ha925a31_3
idna                      3.4              py39haa95532_0
imageio                   2.19.3           py39haa95532_0
intel-openmp              2021.4.0          haa95532_3556
jpeg                      9e                   h2bbff1b_0
kiwisolver                1.4.4            py39hd77b12b_0
lerc                      3.0                  hd77b12b_0
libbrotlicommon           1.0.9                h2bbff1b_7
libbrotlidec              1.0.9                h2bbff1b_7
libbrotlienc              1.0.9                h2bbff1b_7
libclang                  12.0.0          default_h627e005_2
libdeflate                1.8                  h2bbff1b_5
libffi                    3.4.2                hd77b12b_6
libiconv                  1.16                 h2bbff1b_2
libogg                    1.3.5                h2bbff1b_1
libpng                    1.6.37               h2a8f88b_0
libtiff                   4.5.0                h6c2663c_1
libvorbis                 1.3.7                he774522_0
libwebp                   1.2.4                hbc33d0d_1
libwebp-base              1.2.4                h2bbff1b_1
libxml2                   2.9.14               h0ad7f3c_0
libxslt                   1.1.35               h2bbff1b_0
lz4-c                     1.9.4                h2bbff1b_0
matplotlib                3.5.1            py39haa95532_1
matplotlib-base           3.5.1            py39hd77b12b_1
mkl                       2021.4.0           haa95532_640
mkl-service               2.4.0            py39h2bbff1b_0
mkl_fft                   1.3.1            py39h277e83a_0
mkl_random                1.2.2            py39hf11a4ad_0
munkres                   1.1.4                      py_0
ninja                     1.10.2               haa95532_5
ninja-base                1.10.2               h6d14046_5
numpy                     1.23.5           py39h3b20f71_0
numpy-base                1.23.5           py39h4da318b_0
openssl                   1.1.1t               h2bbff1b_0
packaging                 22.0             py39haa95532_0
pcre                      8.45                 hd77b12b_0
pillow                    9.0.1            py39hdc2b20a_0
pip                       22.3.1           py39haa95532_0
ply                       3.11             py39haa95532_0
pooch                     1.4.0              pyhd3eb1b0_0
pycparser                 2.21               pyhd3eb1b0_0
pyopenssl                 22.0.0             pyhd3eb1b0_0
pyparsing                 3.0.9            py39haa95532_0
pyqt                      5.15.7           py39hd77b12b_0
pyqt5-sip                 12.11.0          py39hd77b12b_0
pysocks                   1.7.1            py39haa95532_0
python                    3.9.16               h6244533_0
python-dateutil           2.8.2              pyhd3eb1b0_0
qt-main                   5.15.2               he8e5bd7_7
qt-webengine              5.15.9               hb9a9bb5_5
qtwebkit                  5.212                h3ad3cdb_4
requests                  2.26.0             pyhd3eb1b0_0
scipy                     1.10.0           py39h321e85e_0
setuptools                65.6.3           py39haa95532_0
sip                       6.6.2            py39hd77b12b_0
six                       1.16.0             pyhd3eb1b0_1
sqlite                    3.40.1               h2bbff1b_0
tk                        8.6.12               h2bbff1b_0
toml                      0.10.2             pyhd3eb1b0_0
torch                     1.12.1+cu116             pypi_0    pypi
torchvision               0.13.1+cu116             pypi_0    pypi
tornado                   6.2              py39h2bbff1b_0
tqdm                      4.62.2             pyhd3eb1b0_1
typing-extensions         4.5.0                    pypi_0    pypi
tzdata                    2022g                h04d1e81_0
urllib3                   1.26.14          py39haa95532_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.38.4           py39haa95532_0
win_inet_pton             1.1.0            py39haa95532_0
wincertstore              0.2              py39haa95532_2
xz                        5.2.10               h8cc25b3_1
zlib                      1.2.13               h8cc25b3_0
zstd                      1.5.2                h19a0ad4_0

Traceback (most recent call last):
  File "D:\Anaconda3\envs\stylegan3\lib\site-packages\torch\utils\cpp_extension.py", line 1808, in _run_ninja_build
    subprocess.run(
  File "D:\Anaconda3\envs\stylegan3\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "d:\stylegan3\gen_images.py", line 143, in <module>
    generate_images() # pylint: disable=no-value-for-parameter
  File "D:\Anaconda3\envs\stylegan3\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "D:\Anaconda3\envs\stylegan3\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "D:\Anaconda3\envs\stylegan3\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Anaconda3\envs\stylegan3\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "d:\stylegan3\gen_images.py", line 135, in generate_images
    img = G(z, label, truncation_psi=truncation_psi, noise_mode=noise_mode)
  File "D:\Anaconda3\envs\stylegan3\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "<string>", line 503, in forward
  File "D:\Anaconda3\envs\stylegan3\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "<string>", line 143, in forward
  File "D:\Anaconda3\envs\stylegan3\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "<string>", line 92, in forward
  File "d:\stylegan3\torch_utils\ops\bias_act.py", line 84, in bias_act
    if impl == 'cuda' and x.device.type == 'cuda' and _init():
  File "d:\stylegan3\torch_utils\ops\bias_act.py", line 41, in _init
    _plugin = custom_ops.get_plugin(
  File "d:\stylegan3\torch_utils\custom_ops.py", line 134, in get_plugin
    torch.utils.cpp_extension.load(name=module_name, build_directory=cached_build_dir,
  File "D:\Anaconda3\envs\stylegan3\lib\site-packages\torch\utils\cpp_extension.py", line 1202, in load
    return _jit_compile(
  File "D:\Anaconda3\envs\stylegan3\lib\site-packages\torch\utils\cpp_extension.py", line 1425, in _jit_compile
    _write_ninja_file_and_build_library(
  File "D:\Anaconda3\envs\stylegan3\lib\site-packages\torch\utils\cpp_extension.py", line 1537, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "D:\Anaconda3\envs\stylegan3\lib\site-packages\torch\utils\cpp_extension.py", line 1824, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'bias_act_plugin': [1/2] D:\NVIDIA GPU Computing Toolkit\bin\nvcc --generate-dependencies-with-compile --dependency-output bias_act.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=bias_act_plugin -DTORCH_API_INCLUDE_EXTENSION_H -ID:\Anaconda3\envs\stylegan3\lib\site-packages\torch\include -ID:\Anaconda3\envs\stylegan3\lib\site-packages\torch\include\torch\csrc\api\include -ID:\Anaconda3\envs\stylegan3\lib\site-packages\torch\include\TH -ID:\Anaconda3\envs\stylegan3\lib\site-packages\torch\include\THC "-ID:\NVIDIA GPU Computing Toolkit\include" -ID:\Anaconda3\envs\stylegan3\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --use_fast_math --allow-unsupported-compiler -c C:\Users\程君故\AppData\Local\torch_extensions\torch_extensions\Cache\py39_cu116\bias_act_plugin\d197188c6eb43b2685156af41c1c4adc-nvidia-geforce-gtx-1660-ti\bias_act.cu -o bias_act.cuda.o
FAILED: bias_act.cuda.o
D:\NVIDIA GPU Computing Toolkit\bin\nvcc --generate-dependencies-with-compile --dependency-output bias_act.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=bias_act_plugin -DTORCH_API_INCLUDE_EXTENSION_H -ID:\Anaconda3\envs\stylegan3\lib\site-packages\torch\include -ID:\Anaconda3\envs\stylegan3\lib\site-packages\torch\include\torch\csrc\api\include -ID:\Anaconda3\envs\stylegan3\lib\site-packages\torch\include\TH -ID:\Anaconda3\envs\stylegan3\lib\site-packages\torch\include\THC "-ID:\NVIDIA GPU Computing Toolkit\include" -ID:\Anaconda3\envs\stylegan3\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --use_fast_math --allow-unsupported-compiler -c C:\Users\程君故\AppData\Local\torch_extensions\torch_extensions\Cache\py39_cu116\bias_act_plugin\d197188c6eb43b2685156af41c1c4adc-nvidia-geforce-gtx-1660-ti\bias_act.cu -o bias_act.cuda.o
ninja: build stopped: subcommand failed.

Please copy&paste text instead of screenshots for better searchability.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - PyTorch version 1.12.1
 - CUDA toolkit version 11.6
 - NVIDIA driver version
 - GPU 1660ti

**Additional context**

**Comment by Han-duoduo** [comment]
i meet the same issue
