### ISSUE TITLE
Visualizer stuck when loading pickle

### ISSUE THREAD

**Issue by clbrec** [NVlabs/stylegan3#31]
**Describe the bug**
Upon loading a pickle file, `stylegan3-r-ffhqu-256x256.pkl` in my case, into the visualizer, the program is stuck at `Setting up PyTorch plugin "filtered_lrelu_plugin"...`.

**To Reproduce**
1. Run visualizer.py and load a pickle file. Or use`gen_video.py` with the command: ``` python gen_video.py --output=lerp.mp4 --trunc=1 --seeds=0-31 --grid=4x2 --network=https://api.ngc.nvidia.com/v2/models/nvidia/research/stylegan3/versions/1/files/stylegan3-r-afhqv2-512x512.pkl``` 
2. Error Log:
```
Traceback (most recent call last):
  File "/home/x/Development/stylegan3/viz/renderer.py", line 136, in render
    self._render_impl(res, **args)
  File "/home/x/Development/stylegan3/viz/renderer.py", line 291, in _render_impl
    out, layers = self.run_synthesis_net(G.synthesis, w, capture_layer=layer_name, **synthesis_kwargs)
  File "/home/x/Development/stylegan3/viz/renderer.py", line 370, in run_synthesis_net
    out = net(*args, **kwargs)
  File "/home/x/miniconda3/envs/stylegan3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
    result = forward_call(*input, **kwargs)
  File "<string>", line 463, in forward
  File "/home/x/miniconda3/envs/stylegan3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
    result = forward_call(*input, **kwargs)
  File "<string>", line 347, in forward
  File "/home/x/Development/stylegan3/torch_utils/ops/filtered_lrelu.py", line 119, in filtered_lrelu
    if impl == 'x' and x.device.type == 'cuda' and _init():
  File "/home/x/Development/stylegan3/torch_utils/ops/filtered_lrelu.py", line 27, in _init
    _plugin = custom_ops.get_plugin(
  File "/home/x/Development/stylegan3/torch_utils/custom_ops.py", line 136, in get_plugin
    torch.utils.cpp_extension.load(name=module_name, build_directory=cached_build_dir,
  File "/home/x/miniconda3/envs/stylegan3/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1080, in load
    return _jit_compile(
  File "/home/x/miniconda3/envs/stylegan3/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1318, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/x/miniconda3/envs/stylegan3/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1701, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1173, in create_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
ImportError: /home/x/.cache/torch_extensions/filtered_lrelu_plugin/2e9606d7cf844ec44b9f500eaacd35c0-nvidia-geforce-rtx-3090/filtered_lrelu_plugin.so: cannot open shared object file: No such file or directory
```

**Expected behavior**
Load the chosen pickle file into the visualizer.

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 20.04 LTS
 - Python version: 3.9.7
 - PyTorch version: 1.9.1
 - CUDA toolkit version: 11.4
 - NVIDIA driver version: 470.63.01
 - GPU: RTX 3090
 - Docker: No

**Comment by jannehellsten** [comment]
See if any of the [Things to try tips inTroubleshooting](https://github.com/NVlabs/stylegan3/blob/main/docs/troubleshooting.md) help.

Also try if running `gen_images.py` works successfully.

**Comment by clbrec** [comment]
Deleting `$HOME/.cache/torch_extensions ` seems to have done the trick. Cheers :)
