### ISSUE TITLE
more memory intensive than stylegan2-ada-pytorch? OOM immediately with same dataset that worked before

### ISSUE THREAD

**Issue by MoemaMike** [NVlabs/stylegan3#50]
I have run stylegan2-ada-pytorch training on Colab for several months successfully. Decided to try stylegan3 today but am getting an OOM immediately while trying to retrain a dataset that was not problematic before. Due to the changing hyperparameters i have slightly different command line for stylegan3

Runtime Tesla V100-SXM2
Memory 16gb

!python stylegan3/train.py --snap=8 --aug=ada --mirror=1 --cfg=stylegan3-r --batch=32  --gamma=400 \
--target=0.8 --gpus=1 --metrics='None'  

Constructing networks...
Setting up PyTorch plugin "bias_act_plugin"... Done.
Setting up PyTorch plugin "filtered_lrelu_plugin"... Done.
Traceback (most recent call last):
  File "stylegan3/train.py", line 286, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "stylegan3/train.py", line 281, in main
    launch_training(c=c, desc=desc, outdir=opts.outdir, dry_run=opts.dry_run)
  File "stylegan3/train.py", line 96, in launch_training
    subprocess_fn(rank=0, c=c, temp_dir=temp_dir)
  File "stylegan3/train.py", line 47, in subprocess_fn
    training_loop.training_loop(rank=rank, **c)
  File "/content/stylegan3/training/training_loop.py", line 168, in training_loop
    img = misc.print_module_summary(G, [z, c])
  File "/content/stylegan3/torch_utils/misc.py", line 216, in print_module_summary
    outputs = module(*inputs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1071, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/content/stylegan3/training/networks_stylegan3.py", line 512, in forward
    img = self.synthesis(ws, update_emas=update_emas, **synthesis_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1071, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/content/stylegan3/training/networks_stylegan3.py", line 471, in forward
    x = getattr(self, name)(x, w, **layer_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1071, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/content/stylegan3/training/networks_stylegan3.py", line 350, in forward
    padding=self.conv_kernel-1, demodulate=(not self.is_torgb), input_gain=input_gain)
  File "/content/stylegan3/torch_utils/misc.py", line 103, in decorator
    return fn(*args, **kwargs)
  File "/content/stylegan3/training/networks_stylegan3.py", line 62, in modulated_conv2d
    x = conv2d_gradfix.conv2d(input=x, weight=w.to(x.dtype), padding=padding, groups=batch_size)
  File "/content/stylegan3/torch_utils/ops/conv2d_gradfix.py", line 37, in conv2d
    return _conv2d_gradfix(transpose=False, weight_shape=weight.shape, stride=stride, padding=padding, output_padding=0, dilation=dilation, groups=groups).apply(input, weight, bias)
  File "/content/stylegan3/torch_utils/ops/conv2d_gradfix.py", line 119, in forward
    c = (a.transpose(1, 2) if transpose else a) @ b.permute(1, 2, 0, 3).flatten(2)
RuntimeError: CUDA out of memory. Tried to allocate 2.96 GiB (GPU 0; 15.78 GiB total capacity; 12.54 GiB already allocated; 1.78 GiB free; 12.56 GiB reserved in total by PyTorch)

**Comment by MoemaMike** [comment]
already at minimum of 2

**Comment by may5694** [comment]
I mean reducing the parameter num_layers from 14 down to 13 or 12. See https://github.com/NVlabs/stylegan3/blob/a5a69f58294509598714d1e88c9646c3d7c6ec94/training/networks_stylegan3.py#L406

**Comment by wodsoe** [comment]
set the --batch-gpu to 1

**Comment by MoemaMike** [comment]
> set the --batch-gpu to 1 and --mbstd-group to 1

Now we are talking, thanks Wodsoe. Making those changes prevents the OOM. Seems i can get away with 
--batch-gpu=2 --mbstd-group=2

But --batch-gpu=4 --mbstd-group=4 or the default 8 will cause OOM

So thanks for that.
