### ISSUE TITLE
Issue with StyleGan2 .pkl File + gen_images.py

### ISSUE THREAD

**Issue by EuphoricPenguin** [NVlabs/stylegan3#51]
I'm encountering an error while attempting to generate images from a StyleGan2 .pkl file.

Here is the full command and error printout:

```
(stylegan3) C:\Users\Mars\Documents\stylegan3>python gen_images.py --network "./TADNE-512.pkl" --seeds "1-10" --outdir "./TADNE-Images/"
Loading networks from "./TADNE-512.pkl"...
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0'
Traceback (most recent call last):
  File "C:\Users\Mars\Documents\stylegan3\gen_images.py", line 143, in <module>
    generate_images() # pylint: disable=no-value-for-parameter
  File "C:\Users\Mars\miniconda3\envs\stylegan3\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Mars\miniconda3\envs\stylegan3\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Users\Mars\miniconda3\envs\stylegan3\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Mars\miniconda3\envs\stylegan3\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Mars\Documents\stylegan3\gen_images.py", line 108, in generate_images
    G = legacy.load_network_pkl(f)['G_ema'].to(device) # type: ignore
  File "C:\Users\Mars\Documents\stylegan3\legacy.py", line 28, in load_network_pkl
    G = convert_tf_generator(tf_G)
  File "C:\Users\Mars\Documents\stylegan3\legacy.py", line 155, in convert_tf_generator
    raise ValueError('Unknown TensorFlow kwarg', unknown_kwargs[0])
ValueError: ('Unknown TensorFlow kwarg', 'resolution_w')
```
I'm running miniconda 4.8.3 on Windows 10 19043.1288. Since I'm not training, I decided to poke around with some basic image generation using my GTX 1650. I'm on driver version 451.67 and CUDA toolkit version 11.3.1. I'm using the versions of packages that are specified in the enviornment.yml file, aside from a few that didn't cooperate (or ones that weren't included). 

For reference, here's a list of the packages I have currently installed in this environment:

```
brotlipy           0.7.0
certifi            2021.10.8
cffi               1.14.6
charset-normalizer 2.0.4
click              8.0.1
clip               1.0
colorama           0.4.4
cryptography       3.4.8
cycler             0.10.0
einops             0.3.2
fonttools          4.25.0
ftfy               6.0.3
glfw               2.2.0
idna               3.2
imageio            2.9.0
imageio-ffmpeg     0.4.3
imgui              1.3.0
importlib-metadata 4.8.1
kiwisolver         1.3.1
matplotlib         3.4.2
mkl-fft            1.3.1
mkl-random         1.2.2
mkl-service        2.4.0
munkres            1.1.4
numpy              1.21.2
olefile            0.46
Pillow             8.3.1
pip                21.2.4
psutil             5.8.0
pycparser          2.20
PyOpenGL           3.1.5
pyOpenSSL          20.0.1
pyparsing          2.4.7
PySocks            1.7.1
pyspng             0.1.0
python-dateutil    2.8.2
regex              2021.10.23
requests           2.26.0
scipy              1.7.1
setuptools         58.0.4
sip                4.19.13
six                1.16.0
torch              1.10.0
torchvision        0.11.1
tornado            6.1
tqdm               4.62.2
typing-extensions  3.10.0.2
urllib3            1.26.7
wcwidth            0.2.5
wheel              0.37.0
win-inet-pton      1.1.0
wincertstore       0.2
zipp               3.6.0
```

I can see from the printout that it's trying to load the pickle file using the proper legacy functions, although for some reason a ValueError is creeping in. While that's self-evident, I have no clue why this would be happening. In my experience, a limited amount of something like VRAM would throw its respective memory error. Since this is in the TF .pkl (and not PyTorch) format, it should be ready to go in that department. Oh, and I just realized the weird CUDA runtime issue at the top. Running `conda list cudatoolkit` returns 11.3.1, which means it's not finding the CUDA runtime inside of the conda environment? I'm not sure. Any help is appreciated.

**Comment by Harry-KIT** [comment]
Hi @EuphoricPenguin 
Did you generate fake images using StyleGAN-2?
i am facing similar problem but without error

Loading networks from "training-runs/00000-stylegan2-gpus4-batch32-gamma32/network-snapshot-010200.pkl"...
Generating image for seed 1 (0/10000) ...
Setting up PyTorch plugin "bias_act_plugin"...

**Comment by conceptofmind** [comment]
I am running into the same issue. I have CUDA 11.5 installed in the conda environment.

# packages in environment at C:\Users\anaconda3\envs\stylegan3:
#
# Name                    Version                   Build  Channel
cudatoolkit               11.5.0               hfde6d1b_9    nvidia
