### ISSUE TITLE
Crash when attempting to load pickles in GUI.

### ISSUE THREAD

**Issue by SaltyBarnacles** [NVlabs/stylegan3#58]
When I put in the path for the pickle in the 'Pickle' Box, it crashes.
![image](https://user-images.githubusercontent.com/82734261/139748689-eb72e950-1f5d-4573-a084-26eefc466cdc.png)

Here is the error message:
`(stylegan3) D:\Documents\AI\stylegan3-main>python visualizer.py
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1'
D:\ProgramFlies\envs\stylegan3\lib\site-packages\glfw\__init__.py:834: GLFWError: (65545) b'Win32: Failed to convert clipboard to string: The operation completed successfully. '
  warnings.warn(message, GLFWError)
Traceback (most recent call last):
  File "imgui\core.pyx", line 276, in imgui.core._bytes
TypeError: bad argument type for built-in operation
Exception ignored in: 'imgui.core._IO._get_clipboard_text'
Traceback (most recent call last):
  File "imgui\core.pyx", line 276, in imgui.core._bytes
TypeError: bad argument type for built-in operation
Traceback (most recent call last):
  File "D:\Documents\AI\stylegan3-main\visualizer.py", line 332, in <module>
    main()
  File "D:\ProgramFlies\envs\stylegan3\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "D:\ProgramFlies\envs\stylegan3\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "D:\ProgramFlies\envs\stylegan3\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\ProgramFlies\envs\stylegan3\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "D:\Documents\AI\stylegan3-main\visualizer.py", line 326, in main
    viz.draw_frame()
  File "D:\Documents\AI\stylegan3-main\visualizer.py", line 144, in draw_frame
    self._async_renderer.set_args(**self.args)
  File "D:\Documents\AI\stylegan3-main\visualizer.py", line 212, in set_args
    self._set_args_sync(**args)
  File "D:\Documents\AI\stylegan3-main\visualizer.py", line 229, in _set_args_sync
    self._renderer_obj = renderer.Renderer()
  File "D:\Documents\AI\stylegan3-main\viz\renderer.py", line 127, in __init__
    self._start_event   = torch.cuda.Event(enable_timing=True)
  File "D:\ProgramFlies\envs\stylegan3\lib\site-packages\torch\cuda\streams.py", line 139, in __new__
    return super(Event, cls).__new__(
TypeError: object.__new__() takes exactly one argument (the type to instantiate)`

**Comment by clbrec** [comment]
@SaltyBarnacles  have you been able to solve this? Currently having the same issue.

**Comment by everdrone** [comment]
Having the same issue.
The visualizer cannot load the pickle file on windows.

**Comment by datduong** [comment]
I am also having the same problem on windows.

**Comment by SaltyBarnacles** [comment]
> @SaltyBarnacles have you been able to solve this? Currently having the same issue.

I haven't. Have you?

**Comment by jrocktorrens** [comment]
also not working with ubuntu 20.04 - same error:
`TypeError: object.__new__() takes exactly one argument (the type to instantiate)`
i tried loading a pickle with cli command

**Comment by danzeeeman** [comment]
anyone have a solve?
