### ISSUE TITLE
Error when doing python3 visualizer.py

### ISSUE THREAD

**Issue by GreenLimeSia** [NVlabs/stylegan3#66]
I use miniconda to create an env with conda create -f evn.yml.

**Screenshots**
Traceback (most recent call last):
  File "/home1/yangnan/stylegan3/visualizer.py", line 340, in <module>
    main()
  File "/home1/yangnan/miniconda3/envs/stylegan3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home1/yangnan/miniconda3/envs/stylegan3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home1/yangnan/miniconda3/envs/stylegan3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home1/yangnan/miniconda3/envs/stylegan3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home1/yangnan/stylegan3/visualizer.py", line 286, in main
    viz = Visualizer(capture_dir=capture_dir)
  File "/home1/yangnan/stylegan3/visualizer.py", line 34, in __init__
    super().__init__(title='GAN Visualizer', window_width=380, window_height=210)
  File "/home1/yangnan/stylegan3/gui_utils/imgui_window.py", line 38, in __init__
    self._imgui_renderer = _GlfwRenderer(self._glfw_window)
  File "/home1/yangnan/stylegan3/gui_utils/imgui_window.py", line 97, in __init__
    super().__init__(*args, **kwargs)
  File "/home1/yangnan/miniconda3/envs/stylegan3/lib/python3.9/site-packages/imgui/integrations/glfw.py", line 13, in __init__
    super(GlfwRenderer, self).__init__()
  File "/home1/yangnan/miniconda3/envs/stylegan3/lib/python3.9/site-packages/imgui/integrations/opengl.py", line 60, in __init__
    super(ProgrammablePipelineRenderer, self).__init__()
  File "/home1/yangnan/miniconda3/envs/stylegan3/lib/python3.9/site-packages/imgui/integrations/base.py", line 17, in __init__
    self._create_device_objects()
  File "/home1/yangnan/miniconda3/envs/stylegan3/lib/python3.9/site-packages/imgui/integrations/opengl.py", line 108, in _create_device_objects
    self._attrib_location_tex = gl.glGetUniformLocation(self._shader_handle, "Texture")
  File "src/latebind.pyx", line 51, in OpenGL_accelerate.latebind.Curry.__call__
  File "/home1/yangnan/miniconda3/envs/stylegan3/lib/python3.9/site-packages/OpenGL/GL/VERSION/GL_2_0.py", line 430, in glGetUniformLocation
    return baseOperation( program, name )
  File "/home1/yangnan/miniconda3/envs/stylegan3/lib/python3.9/site-packages/OpenGL/platform/baseplatform.py", line 415, in __call__
    return self( *args, **named )
  File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
	err = 1282,
	description = b'invalid operation',
	baseOperation = glGetUniformLocation,
	cArguments = (1, b'Texture\x00'),
	result = -1
)

<img width="425" alt="1636859260(1)" src="https://user-images.githubusercontent.com/28706611/141665899-7e25e5ec-985f-460b-8896-84a9b67bdc42.png">

**Desktop (please complete the following information):**
 - OS: [e.g. Linux Ubuntu 20.04]
 - PyTorch version (e.g., pytorch 1.9.0)
 - CUDA toolkit version (e.g., CUDA 11.4)
 - NVIDIA driver version
 - GPU [e.g., Titan RTX]
 - Docker: did you use Docker? No
**Additional context**

**Comment by Qingcsai** [comment]
I meet exactly the same error when running `python visualizer.py` as: 
> OpenGL.error.GLError: GLError(
>         err = 1282,
>         description = b'invalid operation',
>         baseOperation = glGetUniformLocation,
>         cArguments = (1, b'Texture\x00'),
>         result = -1
> )

Desktop (please complete the following information):

OS: [e.g. Linux Ubuntu 18.04]
PyTorch version (e.g., pytorch 1.8.0)
CUDA toolkit version (e.g., CUDA 11.4)
NVIDIA driver version
GPU [e.g., GeForce GTX TITAN X]
Docker: did you use Docker? No
Additional context
Add any other context about the problem here.

**Comment by GreenLimeSia** [comment]
Do you fix the above problems after changing pytorch1.8.0 and Ubuntu18.04? @Qingcsai

**Comment by Qingcsai** [comment]
> Do you fix the above problems after changing pytorch1.8.0 and Ubuntu18.04? @Qingcsai

Well, it's still not working in my environment for  pytorch1.8.0 and Ubuntu18.04.

**Comment by GreenLimeSia** [comment]
Me too. I cannot solve this problem. @Qingcsai

**Comment by vanga** [comment]
I am seeing the same issue when trying to run this using remote desktop for VM running in GCP..

**Comment by GreenLimeSia** [comment]
I would suggest you do it on Windows 10. It works for me. @vanga

**Comment by vanga** [comment]
Thanks @GreenLimeSia. I have a Mac M1 and I couldn't set up the dependencies, which is why I was trying with a GCP VM with remote desktop where I ran the training.

**Comment by everdrone** [comment]
@GreenLimeSia on Windows 10 is crashing for me right after loading the network, while on ubuntu it works flawlessly

**Comment by GreenLimeSia** [comment]
Thanks for your valuable suggestions, I will try it on local ubuntu. @everdrone

**Comment by arthur-qiu** [comment]
Try it: export MESA_GL_VERSION_OVERRIDE=3.3. It works for me.

**Comment by kabelkavoj** [comment]
Can confim, the solution suggested by @arthur-qiu works for me to. 

Desktop:
OS: WSL2 Ubuntu, Windows 11
PyTorch version: 1.9.1
CUDA: 11.1
NVIDIA driver version: 510.06
GPU:  RTX 3090
Docker: did you use Docker? No

**Comment by pfeducode** [comment]
> 试试看：导出 MESA_GL_VERSION_OVERRIDE=3.3。这个对我有用。

you are right, I use it solve this problem. my System  is Ubuntu20.04

**Comment by jivaklong** [comment]
I try it: export MESA_GL_VERSION_OVERRIDE=3.3.  But the following error still occurred, My computer is configured with MAC 2.4 GHz 8-core Intel Core i9
 
    raise self._errorClass(
OpenGL.error.GLError: GLError(
        err = 1282,
        description = b'invalid operation',
        baseOperation = glGetUniformLocation,
        cArguments = (1, b'Texture\x00'),
        result = -1
)

**Comment by landacorp** [comment]
Same for me on Macbook with M2 Max 32Mb - not working

`
export MESA_GL_VERSION_OVERRIDE=3.3

sh scripts/gui.sh

Traceback (most recent call last):
  File "/Users/vlad/Projects/AI/DragGAN/visualizer_drag.py", line 403, in <module>
    main()
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vlad/Projects/AI/DragGAN/visualizer_drag.py", line 362, in main
    viz = Visualizer(capture_dir=capture_dir)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vlad/Projects/AI/DragGAN/visualizer_drag.py", line 31, in __init__
    super().__init__(title='DragGAN', window_width=3840, window_height=2160)
  File "/Users/vlad/Projects/AI/DragGAN/gui_utils/imgui_window.py", line 38, in __init__
    self._imgui_renderer = _GlfwRenderer(self._glfw_window)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vlad/Projects/AI/DragGAN/gui_utils/imgui_window.py", line 97, in __init__
    super().__init__(*args, **kwargs)
  File "/opt/homebrew/lib/python3.11/site-packages/imgui/integrations/glfw.py", line 12, in __init__
    super(GlfwRenderer, self).__init__()
  File "/opt/homebrew/lib/python3.11/site-packages/imgui/integrations/opengl.py", line 60, in __init__
    super(ProgrammablePipelineRenderer, self).__init__()
  File "/opt/homebrew/lib/python3.11/site-packages/imgui/integrations/base.py", line 17, in __init__
    self._create_device_objects()
  File "/opt/homebrew/lib/python3.11/site-packages/imgui/integrations/opengl.py", line 108, in _create_device_objects
    self._attrib_location_tex = gl.glGetUniformLocation(self._shader_handle, "Texture")
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/OpenGL/latebind.py", line 63, in __call__
    return self.wrapperFunction( self.baseFunction, *args, **named )
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/OpenGL/GL/VERSION/GL_2_0.py", line 430, in glGetUniformLocation
    return baseOperation( program, name )
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/OpenGL/platform/baseplatform.py", line 415, in __call__
    return self( *args, **named )
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/OpenGL/error.py", line 230, in glCheckError
    raise self._errorClass(
OpenGL.error.GLError: GLError(
	err = 1282,
	description = b'invalid operation',
	baseOperation = glGetUniformLocation,
	cArguments = (1, b'Texture\x00'),
	result = -1
)`
