### ISSUE TITLE
Error when resuming 256x256 network

### ISSUE THREAD

**Issue by kgonia** [NVlabs/stylegan3#84]
Resuming training using 256x256 network couse error. It didn't happen on different sizes of network.

```
Resuming from "C:\Users\user_x\Downloads\stylegan3-r-ffhqu-256x256.pkl"
Traceback (most recent call last):
  File "C:/Users/user_x/PycharmProjects/stylegan3-fun/train.py", line 368, in <module>
    main()  # pylint: disable=no-value-for-parameter
  File "C:\Users\user_x\.conda\envs\stylegan3-fun\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\user_x\.conda\envs\stylegan3-fun\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\user_x\.conda\envs\stylegan3-fun\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\user_x\.conda\envs\stylegan3-fun\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:/Users/user_x/PycharmProjects/stylegan3-fun/train.py", line 361, in main
    launch_training(c=c, desc=desc, outdir=opts.outdir, dry_run=opts.dry_run)
  File "C:/Users/user_x/PycharmProjects/stylegan3-fun/train.py", line 101, in launch_training
    subprocess_fn(rank=0, c=c, temp_dir=temp_dir)
  File "C:/Users/user_x/PycharmProjects/stylegan3-fun/train.py", line 49, in subprocess_fn
    training_loop.training_loop(rank=rank, **c)
  File "C:\Users\user_x\PycharmProjects\stylegan3-fun\training\training_loop.py", line 164, in training_loop
    misc.copy_params_and_buffers(resume_data[name], module, require_all=False)
  File "C:\Users\user_x\PycharmProjects\stylegan3-fun\torch_utils\misc.py", line 162, in copy_params_and_buffers
    tensor.copy_(src_tensors[name].detach()).requires_grad_(tensor.requires_grad)
RuntimeError: The size of tensor a (256) must match the size of tensor b (128) at non-singleton dimension 1

Process finished with exit code 1
```

**Comment by datduong** [comment]
There was a question about this, the solution is to use --cbase. Check it out here. `https://github.com/NVlabs/stylegan3/issues/23#issuecomment-970706600`

**Comment by kgonia** [comment]
@datduong thanks, it helped

**Comment by MoemaMike** [comment]
I am not sure but the issue might be related to --cfg=stylegan3-t  . I had trained models on --cfg=stylegan3-r successfully for some time and then tried to resume training with --cfg=stylegan3-t and i encountered this exact runtime error . It was the only thing i changed.
